[workspace]

members = [
    "mg-core",
    "mg-nft",
    "mg-market",
    "mg-sim",
]

[profile.release]
codegen-units=1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
