[package]
name = "mg-nft"
version = "0.1.0"
authors = ["Epam Inc <hello@nearprotocol.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-env = "0.1.9"
mg-core = { path = "../mg-core" }
